swagger: '2.0'
info:
  version: '${api.version}'
  title: '${project.artifactId}'
  x-ibm-name: '${artifactId}'
  description: '${project.artifactId}'
  contact:
    name: Sanket
    email: sanketsw@au1.ibm.com
host: $(catalog.host)
basePath: '/${project.artifactId}/${api.version}'
paths:
  /transactions:
    get:
      responses:
        '200':
          description: 200 OK
    parameters:
      - name: accountNo
        type: string
        required: true
        in: query
        description: Account Number
securityDefinitions:
  clientID:
    description: ''
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - clientID: []
x-ibm-configuration:
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /transactions
              execute:
                - gatewayscript:
                    title: transactions
                    source: "apim.setvariable('operation','transactions');"
      - gatewayscript:
          title: Log Request
          source: >-
            var util = require('${api.framework.dir}/Util.js');

            var apiConfig
            = util.loadApiConfig('${api.framework.dir}/','${api.config.dir}/',apim.getvariable('env.path'),'${project.artifactId}}','${api.version}',
            console);



            // log request headers and Audit Data

            apiConfig.logAuditData(apim, 'Input');
      - gatewayscript:
          title: Setup
          source: >-
            // Load API Config

            var util = require('${api.framework.dir}/Util.js');

            var apiConfig
            = util.loadApiConfig('${api.framework.dir}/','${api.config.dir}/',apim.getvariable('env.path'),'${project.artifactId}}','${api.version}',
            console);



            // get the operation and method being executed

            var operation = apim.getvariable('operation');

            var method  = apim.getvariable('request.verb');



            // set the targetUrl

            apim.setvariable('targetUrl',apiConfig.getOperation(operation).getMethod(method).targetUrl);



            var preTransformMethod = operation + 'PreTransform';

            apim.setvariable('preTransformMethod', preTransformMethod);



            var postTransformMethod = operation + 'PostTransform';

            apim.setvariable('postTransformMethod', postTransformMethod);
      - gatewayscript:
          title: PreTransform
          source: >-
            // Load API Config

            var util = require('${api.framework.dir}/Util.js');

            var apiConfig
            = util.loadApiConfig('${api.framework.dir}/','${api.config.dir}/',apim.getvariable('env.path'),'${project.artifactId}}','${api.version}',
            console);



            var body = apim.getvariable('message.body');

            apiConfig.logPayload(apim, 'Input');



            var transformer = require('${api.config.dir}/Transformations.js');

            var transformMethodName = apim.getvariable('preTransformMethod');

            util.transformAndLog(transformer, transformMethodName,
            '${api.framework.dir}/', apiConfig, apim);



            apim.output('application/json');
      - operation-switch:
          title: Invoke URL switch
          case:
            - operations:
                - verb: get
                  path: /transactions
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: POST
                    cache-response: protocol
                    cache-ttl: 900
                    target-url: $(targetUrl)
          description: Specify target Method and caching options here
      - gatewayscript:
          title: PostTransform
          source: >-
            // Load API Config

            var util = require('${api.framework.dir}/Util.js');

            var apiConfig
            = util.loadApiConfig('${api.framework.dir}/','${api.config.dir}/',apim.getvariable('env.path'),'${project.artifactId}}','${api.version}',
            console);



            var body = apim.getvariable('message.body');

            apiConfig.logPayload(apim, 'InvokeResponse');



            var transformer = require('${api.config.dir}/Transformations.js');

            var transformMethodName = apim.getvariable('postTransformMethod');

            util.transformAndLog(transformer, transformMethodName,
            '${api.framework.dir}/', apiConfig, apim);
          description: Transform Response
      - gatewayscript:
          title: Log Response
          source: >-
            var util = require('${api.framework.dir}/Util.js');

            var apiConfig
            = util.loadApiConfig('${api.framework.dir}/','${api.config.dir}/',apim.getvariable('env.path'),'${project.artifactId}}','${api.version}',
            console);



            // log response headers and Audit Data

            apiConfig.logAuditData(apim, 'Output');
  catalogs:
    catalog-name-1:
      properties:
        new-property-1: ''
  gateway: datapower-gateway
consumes:
  - application/json
schemes:
  - https
produces:
  - application/json
